# Generated by Django 3.1 on 2020-08-27 14:24

from django.db import migrations, models
import markdownfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('busker', '0002_auto_20200827_1402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='note',
        ),
        migrations.AddField(
            model_name='batch',
            name='private_note',
            field=models.TextField(blank=True, help_text='Optional note for private use; will not be displayed to end users.', null=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='public_message',
            field=markdownfield.models.MarkdownField(blank=True, help_text='Optional markdown-formatted message that will be displayed on the download page.', null=True, rendered_field='public_message_rendered'),
        ),
        migrations.AddField(
            model_name='batch',
            name='public_message_rendered',
            field=markdownfield.models.RenderedMarkdownField(default=''),
            preserve_default=False,
        ),
    ]
