# Generated by Django 3.1 on 2020-08-29 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('busker', '0004_downloadcode_last_used_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artist',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='batch',
            options={'ordering': ('-created_date', 'work__artist__name', 'work__title'), 'verbose_name_plural': 'Batches'},
        ),
        migrations.AlterModelOptions(
            name='downloadablework',
            options={'ordering': ('title', 'artist__name')},
        ),
        migrations.AlterModelOptions(
            name='downloadcode',
            options={'ordering': ('-created_date',)},
        ),
        migrations.AlterModelOptions(
            name='file',
            options={'ordering': ('-created_date',)},
        ),
    ]
