# Generated by Django 3.1 on 2020-08-29 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busker', '0008_remove_downloadablework_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='downloadablework',
            name='status',
        ),
        migrations.AddField(
            model_name='downloadablework',
            name='published',
            field=models.BooleanField(choices=[(True, 'Published'), (False, 'Draft')], default=True, help_text='Unchecked items will not be available for download.'),
        ),
    ]
