# Generated by Django 3.1 on 2020-08-29 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busker', '0009_auto_20200829_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadablework',
            name='published',
            field=models.BooleanField(default=True, help_text='DownloadCodes will NOT work if their DownloadableWork is not published.'),
        ),
    ]
