# Generated by Django 3.1 on 2020-08-27 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busker', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batch',
            options={'verbose_name_plural': 'Batches'},
        ),
        migrations.AddField(
            model_name='downloadcode',
            name='max_uses',
            field=models.IntegerField(default=3, help_text='This is typically initially determined when a Batch is originally created, but can be overridden.'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='max_uses',
            field=models.IntegerField(default=3, help_text='The number of times this code can be used. (You may subsequently change this amount on individual codes, but this will be used as the initial value.) (0 = unlimited)'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='number_of_codes',
            field=models.IntegerField(default='100', help_text='The number of Download Codes to be generated with this batch. (Additional codes may be added to the batch later.)'),
        ),
    ]
