# Generated by Django 3.1 on 2020-08-29 18:15

import busker.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busker', '0005_auto_20200829_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadablework',
            name='image',
            field=models.ImageField(blank=True, help_text='An optional image to be displayed on the code redemption screen. (For example album art.)', null=True, upload_to=busker.models.work_image_path),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to=busker.models.work_file_path),
        ),
    ]
