# Generated by Django 3.1 on 2020-08-29 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busker', '0006_auto_20200829_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadablework',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
