# Generated by Django 3.1 on 2020-08-29 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('busker', '0007_downloadablework_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='downloadablework',
            name='thumbnail',
        ),
    ]
