# Generated by Django 3.1.1 on 2020-09-05 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('busker', '0011_auto_20200905_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadcode',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes', to='busker.batch'),
        ),
    ]
