# Generated by Django 3.1.1 on 2020-09-06 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('busker', '0012_auto_20200905_2042'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='downloadcode',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='file',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='busker.downloadablework'),
        ),
    ]
